In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
# Read all four output files

classifier = pd.read_csv(Path('../../../Resources/PythonExport/ML_Export/2019/cl_output_2019.csv'))
classifier = classifier.drop(['Unnamed: 0'], axis=1)

svm = pd.read_csv(Path('../../../Resources/PythonExport/ML_Export/2019/svm_output_2019.csv'))
svm = svm.drop(['Unnamed: 0'], axis=1)

rnf = pd.read_csv(Path('../../../Resources/PythonExport/ML_Export/2019/rnf_output_2019.csv'))
rnf = rnf.drop(['Unnamed: 0'], axis=1)

nn = pd.read_csv(Path('../../../Resources/PythonExport/ML_Export/2019/nn_output_2019.csv'))
nn = nn.drop(['Unnamed: 0'], axis=1)

In [3]:
# Merge all 4 files on result ID
output_2019 = pd.merge(classifier, svm, how='left', on=['resultId'])

In [4]:
output_2019 = pd.merge(output_2019, rnf, how='left', on=['resultId'])

In [5]:
output_2019 = pd.merge(output_2019, nn, how='left', on=['resultId'])
output_2019.head()

,resultId,name,driverRef,constructorRef,Outcome,Bin,CL_Outcome,CL_Bin,SVM_Outcome,SVM_Bin,RNF_Outcome,RNF_Bin,NN_Outcome,NN_Bin
0,24203,Australian Grand Prix,bottas,mercedes,1,1,3,1,16,4,2,1,4,2
1,24204,Australian Grand Prix,hamilton,mercedes,2,1,1,1,1,1,3,1,1,1
2,24205,Australian Grand Prix,max_verstappen,red_bull,3,1,5,2,6,2,7,3,3,1
3,24206,Australian Grand Prix,vettel,ferrari,4,2,2,1,2,1,1,1,2,1
4,24207,Australian Grand Prix,leclerc,ferrari,5,2,6,2,5,2,8,3,8,3

In [6]:
# Extract CSV file
output_2019.to_csv('../../../Resources/PythonExport/ML_Export/2019/output_2019.csv')