In [1]:
import pandas as pd
import psycopg2
from config import *

In [2]:
conn = psycopg2.connect(
   database=DATABASE, user=USER, password=PASSWORD, host=HOST, port= PORT
)

In [3]:
cursor = conn.cursor()

In [4]:
cursor.execute("Select * FROM races LIMIT 0")
colnames = [desc[0] for desc in cursor.description]
colnames

['raceId', 'year', 'round', 'circuitId', 'name', 'date', 'time', 'url']

In [5]:
cursor.execute("SELECT * FROM races")
data = cursor.fetchall()
race_df = pd.DataFrame(data, columns=colnames)
race_df.head()

,raceId,year,round,circuitId,name,date,time,url
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...

In [6]:
cursor.execute("Select * FROM results LIMIT 0")
colnames = [desc[0] for desc in cursor.description]
colnames

['resultId',
 'raceId',
 'driverId',
 'constructorId',
 'number',
 'grid',
 'position',
 'positionText',
 'positionOrder',
 'points',
 'laps',
 'time',
 'milliseconds',
 'fastestLap',
 'rank',
 'fastestLapTime',
 'fastestLapSpeed',
 'statusId']

In [7]:
cursor.execute("SELECT * FROM results")
data = cursor.fetchall()
results_df = pd.DataFrame(data, columns=colnames)
results_df.head()

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1

In [8]:
raceresults_df = results_df.merge(race_df,left_on='raceId',right_on='raceId',how='left')

In [9]:
raceresults_df = raceresults_df.dropna().reset_index()

In [10]:
raceresults_df.head()

,index,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,...,fastestLapTime,fastestLapSpeed,statusId,year,round,circuitId,name,date,time_y,url
0,0,1,18,1,1,22,1,1,1,1,...,1:27.452,218.300,1,2008,1,1,Australian Grand Prix,2008-03-16,04:30:00,http://en.wikipedia.org/wiki/2008_Australian_G...
1,1,2,18,2,2,3,5,2,2,2,...,1:27.739,217.586,1,2008,1,1,Australian Grand Prix,2008-03-16,04:30:00,http://en.wikipedia.org/wiki/2008_Australian_G...
2,2,3,18,3,3,7,7,3,3,3,...,1:28.090,216.719,1,2008,1,1,Australian Grand Prix,2008-03-16,04:30:00,http://en.wikipedia.org/wiki/2008_Australian_G...
3,3,4,18,4,4,5,11,4,4,4,...,1:28.603,215.464,1,2008,1,1,Australian Grand Prix,2008-03-16,04:30:00,http://en.wikipedia.org/wiki/2008_Australian_G...
4,4,5,18,5,1,23,3,5,5,5,...,1:27.418,218.385,1,2008,1,1,Australian Grand Prix,2008-03-16,04:30:00,http://en.wikipedia.org/wiki/2008_Australian_G...

In [11]:
file_path = "../Resources/PythonExport/weather.csv"
weather_df = pd.read_csv(file_path)
weather_df.head()

,Unnamed: 0,raceId,year,round,weather,weather_warm,weather_cold,weather_dry,weather_wet,weather_cloudy
0,0,1,2009,1,Sunny with temperatures reaching up to 27 °C (...,1,0,0,0,0
1,1,2,2009,2,"Dry start, with heavy rain and thunderstorm/mo...",0,0,1,1,0
2,2,3,2009,3,Rain,0,0,0,1,0
3,3,4,2009,4,Sunny,1,0,0,0,0
4,4,5,2009,5,"Warm, Sunny",1,0,0,0,0

In [12]:
df = raceresults_df.merge(weather_df,left_on='raceId',right_on='raceId',how='left')
df.head()

,index,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,...,url,Unnamed: 0,year_y,round_y,weather,weather_warm,weather_cold,weather_dry,weather_wet,weather_cloudy
0,0,1,18,1,1,22,1,1,1,1,...,http://en.wikipedia.org/wiki/2008_Australian_G...,17,2008,1,"Sunny,very hot with air temperature 39°C.",1,0,0,0,0
1,1,2,18,2,2,3,5,2,2,2,...,http://en.wikipedia.org/wiki/2008_Australian_G...,17,2008,1,"Sunny,very hot with air temperature 39°C.",1,0,0,0,0
2,2,3,18,3,3,7,7,3,3,3,...,http://en.wikipedia.org/wiki/2008_Australian_G...,17,2008,1,"Sunny,very hot with air temperature 39°C.",1,0,0,0,0
3,3,4,18,4,4,5,11,4,4,4,...,http://en.wikipedia.org/wiki/2008_Australian_G...,17,2008,1,"Sunny,very hot with air temperature 39°C.",1,0,0,0,0
4,4,5,18,5,1,23,3,5,5,5,...,http://en.wikipedia.org/wiki/2008_Australian_G...,17,2008,1,"Sunny,very hot with air temperature 39°C.",1,0,0,0,0

In [13]:
df.drop(columns=['index','resultId','raceId','url','time_y','date','round_y','position','positionText','number','points','laps','time_x','milliseconds','fastestLap','rank','year_y','Unnamed: 0','weather','round_x','name','fastestLapSpeed','fastestLapTime'],inplace=True)

In [14]:
df

,driverId,constructorId,grid,positionOrder,statusId,year_x,circuitId,weather_warm,weather_cold,weather_dry,weather_wet,weather_cloudy
0,1,1,1,1,1,2008,1,1,0,0,0,0
1,2,2,5,2,1,2008,1,1,0,0,0,0
2,3,3,7,3,1,2008,1,1,0,0,0,0
3,4,4,11,4,1,2008,1,1,0,0,0,0
4,5,1,3,5,1,2008,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25035,849,3,19,16,11,2021,4,0,0,0,0,1
25036,4,214,10,17,11,2021,4,0,0,0,0,1
25037,854,210,18,18,12,2021,4,0,0,0,0,1
25038,853,210,20,19,12,2021,4,0,0,0,0,1
25039,852,213,16,20,10,2021,4,0,0,0,0,1

In [15]:
df.dtypes

driverId          int64
constructorId     int64
grid              int64
positionOrder     int64
statusId          int64
year_x            int64
circuitId         int64
weather_warm      int64
weather_cold      int64
weather_dry       int64
weather_wet       int64
weather_cloudy    int64
dtype: object

In [16]:
# We will finish all the statuses where drivers finish the race to 2
replace = {
    11:2, 12:2, 13:2, 14:2, 15:2, 16:2, 17:2, 18:2, 19:2, 45:2, 50:2, 128:2, 53:2, 55:2, 58:2, 
    88:2, 111:2, 112:2, 113:2, 114:2, 115:2, 116:2, 117:2, 118:2, 119:2, 120:2, 122:2, 123:2, 124:2, 
    125:2, 127:2, 133:2, 134:2  
}
df["statusId"] = df["statusId"].replace(replace)

In [17]:
# Transform finish_status column. Anything which is not 1 (driver did not finish race) is converted to 3
def change_status(x):
    if x == 1:
        return 1
    elif x == 2:
        return 2
    else:
        return 3
    
df["statusId"] = df["statusId"].apply(change_status)
df.tail(10)

,driverId,constructorId,grid,positionOrder,statusId,year_x,circuitId,weather_warm,weather_cold,weather_dry,weather_wet,weather_cloudy
25030,840,117,11,11,2,2021,4,0,0,0,0,1
25031,8,51,17,12,2,2021,4,0,0,0,0,1
25032,20,117,13,13,2,2021,4,0,0,0,0,1
25033,847,3,15,14,2,2021,4,0,0,0,0,1
25034,841,51,14,15,2,2021,4,0,0,0,0,1
25035,849,3,19,16,2,2021,4,0,0,0,0,1
25036,4,214,10,17,2,2021,4,0,0,0,0,1
25037,854,210,18,18,2,2021,4,0,0,0,0,1
25038,853,210,20,19,2,2021,4,0,0,0,0,1
25039,852,213,16,20,3,2021,4,0,0,0,0,1

In [18]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(sparse=False)

# Fit the encoder and produce encoded DataFrame
encode_df = pd.DataFrame(enc.fit_transform(df.statusId.values.reshape(-1,1)))

# Rename encoded columns
encode_df.columns = enc.get_feature_names(['statusId'])
encode_df.head()

   statusId_1  statusId_2  statusId_3
0         1.0         0.0         0.0
1         1.0         0.0         0.0
2         1.0         0.0         0.0
3         1.0         0.0         0.0
4         1.0         0.0         0.0

In [19]:
df = df.merge(encode_df,left_index=True,right_index=True).drop("statusId",1)

In [20]:
# # Fit the encoder and produce encoded DataFrame
# encode_df = pd.DataFrame(enc.fit_transform(df.grid.values.reshape(-1,1)))
# # Rename encoded columns
# encode_df.columns = enc.get_feature_names(['grid'])
# df = df.merge(encode_df,left_index=True,right_index=True).drop("grid",1)

In [21]:
# Fit the encoder and produce encoded DataFrame
encode_df = pd.DataFrame(enc.fit_transform(df.driverId.values.reshape(-1,1)))
# Rename encoded columns
encode_df.columns = enc.get_feature_names(['driverId'])
df = df.merge(encode_df,left_index=True,right_index=True).drop("driverId",1)

In [22]:
constructorId = df[df['year_x']==2019]['constructorId']
constructor_df = constructorId.to_frame().reset_index().drop(columns=['index'])

In [23]:
# Fit the encoder and produce encoded DataFrame
encode_df = pd.DataFrame(enc.fit_transform(df.constructorId.values.reshape(-1,1)))
# Rename encoded columns
encode_df.columns = enc.get_feature_names(['constructorId'])
df = df.merge(encode_df,left_index=True,right_index=True).drop("constructorId",1)

In [24]:
# df.head()
circuitId = df[df['year_x']==2019]['circuitId']
circuitId_df = circuitId.to_frame().reset_index().drop(columns=['index'])

In [25]:
# # Fit the encoder and produce encoded DataFrame
# encode_df = pd.DataFrame(enc.fit_transform(df.circuitId.values.reshape(-1,1)))
# # Rename encoded columns
# encode_df.columns = enc.get_feature_names(['circuitId'])
# df = df.merge(encode_df,left_index=True,right_index=True).drop("circuitId",1)

In [26]:
# Transform finish_status column. Anything which is not 1 (driver did not finish race) is converted to 3
podium = [1,2,3]
def change_order(x):
    if x == 1:
        return 1
    else:
        return 0

def podium_order(x):
    if x in podium:
        return x
    else:
        return 0
df["podium"] = df["positionOrder"].apply(podium_order)    
df["positionOrder"] = df["positionOrder"].apply(change_order)

df.head(10)

,grid,positionOrder,year_x,circuitId,weather_warm,weather_cold,weather_dry,weather_wet,weather_cloudy,statusId_1,...,constructorId_205,constructorId_206,constructorId_207,constructorId_208,constructorId_209,constructorId_210,constructorId_211,constructorId_213,constructorId_214,podium
0,1,1,2008,1,1,0,0,0,0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1,5,0,2008,1,1,0,0,0,0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
2,7,0,2008,1,1,0,0,0,0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
3,11,0,2008,1,1,0,0,0,0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,3,0,2008,1,1,0,0,0,0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
5,13,0,2008,1,1,0,0,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
6,17,0,2008,1,1,0,0,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
7,15,0,2008,1,1,0,0,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
8,2,0,2008,1,1,0,0,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
9,18,0,2008,1,1,0,0,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [27]:
import sklearn as skl
from sklearn import preprocessing
X_scaler = skl.preprocessing.StandardScaler()

In [28]:
df_train = df[(df['year_x']<=2018) & (df['year_x']>=2000)]
df_test = df[df['year_x']==2019]

In [29]:
df_train

,grid,positionOrder,year_x,circuitId,weather_warm,weather_cold,weather_dry,weather_wet,weather_cloudy,statusId_1,...,constructorId_205,constructorId_206,constructorId_207,constructorId_208,constructorId_209,constructorId_210,constructorId_211,constructorId_213,constructorId_214,podium
0,1,1,2008,1,1,0,0,0,0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1,5,0,2008,1,1,0,0,0,0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
2,7,0,2008,1,1,0,0,0,0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
3,11,0,2008,1,1,0,0,0,0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,3,0,2008,1,1,0,0,0,0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24192,17,0,2018,24,0,0,0,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
24193,9,0,2018,24,0,0,0,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
24194,12,0,2018,24,0,0,0,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
24195,4,0,2018,24,0,0,0,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
24196,10,0,2018,24,0,0,0,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [30]:
y_train= df_train['positionOrder']
y_test= df_test['positionOrder']
X_train = df_train.drop(columns=['positionOrder','podium'])
# .drop(columns=['positionOrder','driverId','constructorId','circuitId','year_x'])
X_test = df_test.drop(columns=['positionOrder','podium'])
# X_test = df_test.drop(columns=['positionOrder','driverId','constructorId','circuitId','year_x'])

In [31]:
X_scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [32]:
X_test_scaled

array([[-1.46612311,  1.77603196, -0.90957457, ...,  0.        ,
         0.        ,  0.        ],
       [-1.62545438,  1.77603196, -0.90957457, ...,  0.        ,
         0.        ,  0.        ],
       [-1.14746058,  1.77603196, -0.90957457, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.03214169,  1.77603196,  0.52039941, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.24250846,  1.77603196,  0.52039941, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.12718958,  1.77603196,  0.52039941, ...,  1.        ,
         0.        ,  0.        ]])

In [33]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs', random_state=1,max_iter=300)
classifier

LogisticRegression(max_iter=300, random_state=1)

In [34]:
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=300, random_state=1)

In [35]:
predictions = classifier.predict_proba(X_test)
predictions
# test = pd.DataFrame({"Prediction": predictions, "Actual": y_test})
# test

array([[8.71348400e-01, 1.28651600e-01],
       [4.03699493e-01, 5.96300507e-01],
       [8.70628150e-01, 1.29371850e-01],
       [7.80450619e-01, 2.19549381e-01],
       [9.50956475e-01, 4.90435251e-02],
       [9.90104123e-01, 9.89587737e-03],
       [9.99919151e-01, 8.08485372e-05],
       [9.99736738e-01, 2.63262077e-04],
       [9.99995514e-01, 4.48568228e-06],
       [9.99994099e-01, 5.90057644e-06],
       [9.99994076e-01, 5.92402340e-06],
       [9.99472297e-01, 5.27703195e-04],
       [9.99902051e-01, 9.79489612e-05],
       [9.99980054e-01, 1.99462113e-05],
       [9.99986222e-01, 1.37777553e-05],
       [9.99999242e-01, 7.58303364e-07],
       [9.99999649e-01, 3.51171575e-07],
       [9.99814518e-01, 1.85482498e-04],
       [9.99984130e-01, 1.58696601e-05],
       [9.99999465e-01, 5.34857933e-07],
       [6.59119924e-01, 3.40880076e-01],
       [9.50845475e-01, 4.91545250e-02],
       [6.83764357e-01, 3.16235643e-01],
       [9.17998561e-01, 8.20014393e-02],
       [6.67345048e-01, 3.32654952e-01],
       [9.93535631e-01, 6.46436942e-03],
       [9.90525065e-01, 9.47493525e-03],
       [9.98912119e-01, 1.08788079e-03],
       [9.99275960e-01, 7.24040146e-04],
       [9.99761529e-01, 2.38471232e-04],
       [9.99901117e-01, 9.88833281e-05],
       [9.99993910e-01, 6.08988280e-06],
       [9.99136815e-01, 8.63184816e-04],
       [9.99998429e-01, 1.57057970e-06],
       [9.99999217e-01, 7.82631905e-07],
       [9.99999638e-01, 3.62438168e-07],
       [9.99999132e-01, 8.68473957e-07],
       [9.99951722e-01, 4.82783589e-05],
       [9.99789125e-01, 2.10875296e-04],
       [9.99987165e-01, 1.28345773e-05],
       [5.39414666e-01, 4.60585334e-01],
       [7.98985641e-01, 2.01014359e-01],
       [7.81740967e-01, 2.18259033e-01],
       [9.20896066e-01, 7.91039340e-02],
       [9.19219759e-01, 8.07802405e-02],
       [9.55974565e-01, 4.40254349e-02],
       [9.99119282e-01, 8.80718092e-04],
       [9.99967019e-01, 3.29811842e-05],
       [9.99969922e-01, 3.00776160e-05],
       [9.78189626e-01, 2.18103741e-02],
       [9.99920510e-01, 7.94903409e-05],
       [9.99995548e-01, 4.45195832e-06],
       [9.99835870e-01, 1.64130380e-04],
       [9.99982696e-01, 1.73035030e-05],
       [9.99999083e-01, 9.16633422e-07],
       [9.99997782e-01, 2.21844817e-06],
       [9.99998973e-01, 1.02736792e-06],
       [9.99996824e-01, 3.17638608e-06],
       [9.99986437e-01, 1.35634715e-05],
       [9.99891757e-01, 1.08242503e-04],
       [8.03194288e-01, 1.96805712e-01],
       [5.45969677e-01, 4.54030323e-01],
       [7.86214059e-01, 2.13785941e-01],
       [8.74405275e-01, 1.25594725e-01],
       [9.90245858e-01, 9.75414174e-03],
       [9.71857743e-01, 2.81422566e-02],
       [9.94872564e-01, 5.12743636e-03],
       [9.82354567e-01, 1.76454334e-02],
       [9.99550360e-01, 4.49639658e-04],
       [9.68059912e-01, 3.19400879e-02],
       [9.99943170e-01, 5.68303479e-05],
       [9.99997368e-01, 2.63152982e-06],
       [9.99968410e-01, 3.15899520e-05],
       [9.99991005e-01, 8.99468950e-06],
       [9.99996290e-01, 3.70953784e-06],
       [9.83466143e-01, 1.65338573e-02],
       [9.85282393e-01, 1.47176071e-02],
       [9.99997625e-01, 2.37517998e-06],
       [9.99802971e-01, 1.97029422e-04],
       [9.99954784e-01, 4.52158604e-05],
       [5.37890931e-01, 4.62109069e-01],
       [7.97999056e-01, 2.02000944e-01],
       [8.70787442e-01, 1.29212558e-01],
       [7.80692976e-01, 2.19307024e-01],
       [9.51022425e-01, 4.89775749e-02],
       [9.55715781e-01, 4.42842190e-02],
       [9.94220379e-01, 5.77962142e-03],
       [9.98949046e-01, 1.05095359e-03],
       [9.96915779e-01, 3.08422063e-03],
       [9.91769984e-01, 8.23001608e-03],
       [9.98797824e-01, 1.20217554e-03],
       [9.99290630e-01, 7.09369578e-04],
       [6.12586038e-01, 3.87413962e-01],
       [9.99638780e-01, 3.61219898e-04],
       [9.99865597e-01, 1.34403296e-04],
       [9.99967541e-01, 3.24592483e-05],
       [9.99999243e-01, 7.57231138e-07],
       [9.99998225e-01, 1.77472381e-06],
       [9.99998806e-01, 1.19399871e-06],
       [9.99952325e-01, 4.76746818e-05],
       [3.89960737e-01, 6.10039263e-01],
       [8.52129908e-01, 1.47870092e-01],
       [8.64775156e-01, 1.35224844e-01],
       [7.87279963e-01, 2.12720037e-01],
       [9.83601672e-01, 1.63983280e-02],
       [9.94384794e-01, 5.61520587e-03],
       [9.90420662e-01, 9.57933764e-03],
       [9.97813114e-01, 2.18688598e-03],
       [9.67953901e-01, 3.20460990e-02],
       [9.99656496e-01, 3.43504040e-04],
       [9.98682475e-01, 1.31752525e-03],
       [9.98480237e-01, 1.51976292e-03],
       [9.99995949e-01, 4.05058202e-06],
       [9.99914375e-01, 8.56248891e-05],
       [9.99999197e-01, 8.03106043e-07],
       [9.99997233e-01, 2.76704996e-06],
       [9.99981306e-01, 1.86944862e-05],
       [9.99999628e-01, 3.71919780e-07],
       [9.99998321e-01, 1.67936426e-06],
       [9.99996809e-01, 3.19127914e-06],
       [5.38242626e-01, 4.61757374e-01],
       [5.47381536e-01, 4.52618464e-01],
       [8.68363077e-01, 1.31636923e-01],
       [9.83337952e-01, 1.66620478e-02],
       [9.90164993e-01, 9.83500726e-03],
       [9.95537767e-01, 4.46223329e-03],
       [9.99299928e-01, 7.00072216e-04],
       [9.96139738e-01, 3.86026214e-03],
       [9.99997395e-01, 2.60530218e-06],
       [9.99912231e-01, 8.77689244e-05],
       [9.99912021e-01, 8.79788521e-05],
       [9.99993452e-01, 6.54786270e-06],
       [9.99959503e-01, 4.04969389e-05],
       [9.99990808e-01, 9.19230750e-06],
       [9.99994029e-01, 5.97139388e-06],
       [9.99998702e-01, 1.29824272e-06],
       [9.79068450e-01, 2.09315499e-02],
       [9.99999399e-01, 6.01218582e-07],
       [9.99994698e-01, 5.30183459e-06],
       [9.99859681e-01, 1.40319303e-04],
       [3.99624132e-01, 6.00375868e-01],
       [8.69435458e-01, 1.30564542e-01],
       [8.66084666e-01, 1.33915334e-01],
       [8.68706112e-01, 1.31293888e-01],
       [9.68120464e-01, 3.18795361e-02],
       [9.73287560e-01, 2.67124398e-02],
       [9.99947080e-01, 5.29197346e-05],
       [9.99972102e-01, 2.78981458e-05],
       [9.97289613e-01, 2.71038736e-03],
       [9.99545301e-01, 4.54698849e-04],
       [9.99474115e-01, 5.25885170e-04],
       [9.99988533e-01, 1.14665614e-05],
       [9.99997343e-01, 2.65736778e-06],
       [9.99999309e-01, 6.90704853e-07],
       [9.99940201e-01, 5.97987391e-05],
       [9.99878251e-01, 1.21748849e-04],
       [9.99993432e-01, 6.56819860e-06],
       [9.99998947e-01, 1.05285356e-06],
       [9.99999551e-01, 4.49226615e-07],
       [9.99999152e-01, 8.47863262e-07],
       [7.02251204e-01, 2.97748796e-01],
       [6.97463716e-01, 3.02536284e-01],
       [9.23153980e-01, 7.68460203e-02],
       [9.89480215e-01, 1.05197847e-02],
       [7.79716010e-01, 2.20283990e-01],
       [9.97420178e-01, 2.57982196e-03],
       [9.99257250e-01, 7.42749529e-04],
       [9.99998869e-01, 1.13128916e-06],
       [9.98711645e-01, 1.28835453e-03],
       [9.99413874e-01, 5.86126276e-04],
       [9.99981264e-01, 1.87358649e-05],
       [9.99942373e-01, 5.76271470e-05],
       [9.99990993e-01, 9.00742572e-06],
       [9.99987201e-01, 1.27989793e-05],
       [9.99998706e-01, 1.29426633e-06],
       [9.99954842e-01, 4.51575722e-05],
       [9.99996673e-01, 3.32674443e-06],
       [9.79264668e-01, 2.07353321e-02],
       [9.99906756e-01, 9.32440393e-05],
       [9.99998280e-01, 1.72032850e-06],
       [5.23595356e-01, 4.76404644e-01],
       [7.88587431e-01, 2.11412569e-01],
       [8.61492766e-01, 1.38507234e-01],
       [9.22292815e-01, 7.77071845e-02],
       [8.64190004e-01, 1.35809996e-01],
       [9.99351446e-01, 6.48554074e-04],
       [9.81107886e-01, 1.88921140e-02],
       [9.98873183e-01, 1.12681657e-03],
       [9.99956603e-01, 4.33970854e-05],
       [9.96999379e-01, 3.00062092e-03],
       [9.88682704e-01, 1.13172961e-02],
       [9.96256518e-01, 3.74348224e-03],
       [9.99967009e-01, 3.29912322e-05],
       [9.99999198e-01, 8.01970466e-07],
       [9.99999629e-01, 3.71393893e-07],
       [9.97140562e-01, 2.85943783e-03],
       [9.99993055e-01, 6.94454571e-06],
       [9.99980343e-01, 1.96565058e-05],
       [9.99997401e-01, 2.59872481e-06],
       [9.99998940e-01, 1.06034156e-06],
       [6.83516521e-01, 3.16483479e-01],
       [9.99969614e-01, 3.03855431e-05],
       [9.99780515e-01, 2.19485481e-04],
       [9.99833136e-01, 1.66863792e-04],
       [9.83657439e-01, 1.63425606e-02],
       [9.99914598e-01, 8.54018677e-05],
       [9.85142152e-01, 1.48578477e-02],
       [9.99292273e-01, 7.07726744e-04],
       [3.90409646e-01, 6.09590354e-01],
       [9.99977569e-01, 2.24313843e-05],
       [9.99951564e-01, 4.84360353e-05],
       [9.52759279e-01, 4.72407214e-02],
       [9.98491250e-01, 1.50874975e-03],
       [9.98123489e-01, 1.87651068e-03],
       [9.98819365e-01, 1.18063530e-03],
       [9.99932848e-01, 6.71523932e-05],
       [9.99952484e-01, 4.75156980e-05],
       [9.99999611e-01, 3.89362173e-07],
       [9.99990229e-01, 9.77099206e-06],
       [9.99918644e-01, 8.13561562e-05],
       [6.59967199e-01, 3.40032801e-01],
       [5.63942179e-01, 4.36057821e-01],
       [9.10643403e-01, 8.93565971e-02],
       [9.16555476e-01, 8.34445238e-02],
       [9.99541068e-01, 4.58932273e-04],
       [9.97678067e-01, 2.32193291e-03],
       [9.99842323e-01, 1.57676816e-04],
       [9.92649048e-01, 7.35095184e-03],
       [9.99068823e-01, 9.31177373e-04],
       [9.99964790e-01, 3.52104707e-05],
       [9.99996068e-01, 3.93245182e-06],
       [9.99916872e-01, 8.31279433e-05],
       [9.99988600e-01, 1.13998116e-05],
       [9.99999189e-01, 8.10819344e-07],
       [9.99982117e-01, 1.78833744e-05],
       [9.99993225e-01, 6.77462051e-06],
       [9.99998435e-01, 1.56466463e-06],
       [9.99997201e-01, 2.79919102e-06],
       [9.99999380e-01, 6.19922335e-07],
       [9.99962311e-01, 3.76891576e-05],
       [6.78874230e-01, 3.21125770e-01],
       [6.54041523e-01, 3.45958477e-01],
       [9.49782048e-01, 5.02179515e-02],
       [6.62326407e-01, 3.37673593e-01],
       [9.99869264e-01, 1.30735719e-04],
       [9.89385927e-01, 1.06140733e-02],
       [9.99985305e-01, 1.46949901e-05],
       [9.98981948e-01, 1.01805245e-03],
       [9.99576992e-01, 4.23007888e-04],
       [9.99902941e-01, 9.70589801e-05],
       [9.99970646e-01, 2.93537875e-05],
       [9.99700328e-01, 2.99671727e-04],
       [9.99854855e-01, 1.45144812e-04],
       [9.99814781e-01, 1.85219224e-04],
       [9.99988059e-01, 1.19411213e-05],
       [9.98595199e-01, 1.40480077e-03],
       [9.81971558e-01, 1.80284417e-02],
       [9.99999554e-01, 4.46169627e-07],
       [9.99997143e-01, 2.85732765e-06],
       [9.98813460e-01, 1.18654006e-03],
       [6.78977045e-01, 3.21022955e-01],
       [9.16813407e-01, 8.31865931e-02],
       [5.24183586e-01, 4.75816414e-01],
       [9.46407719e-01, 5.35922805e-02],
       [9.74574139e-01, 2.54258613e-02],
       [9.83341713e-01, 1.66582869e-02],
       [9.99971937e-01, 2.80630765e-05],
       [9.99952778e-01, 4.72220678e-05],
       [9.99873704e-01, 1.26295988e-04],
       [9.99992621e-01, 7.37852383e-06],
       [9.99997625e-01, 2.37468622e-06],
       [9.99791922e-01, 2.08078206e-04],
       [9.91637476e-01, 8.36252406e-03],
       [9.99988065e-01, 1.19354905e-05],
       [9.65237753e-01, 3.47622468e-02],
       [9.99983301e-01, 1.66987407e-05],
       [9.99994473e-01, 5.52737908e-06],
       [9.99984219e-01, 1.57806948e-05],
       [9.99991602e-01, 8.39845817e-06],
       [9.99784424e-01, 2.15575945e-04],
       [7.81579973e-01, 2.18420027e-01],
       [6.91962011e-01, 3.08037989e-01],
       [8.71370087e-01, 1.28629913e-01],
       [5.39180292e-01, 4.60819708e-01],
       [9.71834255e-01, 2.81657452e-02],
       [9.55094689e-01, 4.49053112e-02],
       [9.93776295e-01, 6.22370533e-03],
       [9.98827418e-01, 1.17258203e-03],
       [9.91735562e-01, 8.26443820e-03],
       [9.97567912e-01, 2.43208796e-03],
       [9.99962906e-01, 3.70935602e-05],
       [9.84626616e-01, 1.53733837e-02],
       [9.99908657e-01, 9.13428164e-05],
       [9.99983941e-01, 1.60592490e-05],
       [9.99793731e-01, 2.06268643e-04],
       [9.99987722e-01, 1.22783490e-05],
       [9.99612489e-01, 3.87511182e-04],
       [9.99986222e-01, 1.37781463e-05],
       [9.99998261e-01, 1.73880697e-06],
       [9.99999655e-01, 3.44751393e-07],
       [5.30884267e-01, 4.69115733e-01],
       [9.51070900e-01, 4.89291004e-02],
       [6.84808608e-01, 3.15191392e-01],
       [9.89872765e-01, 1.01272349e-02],
       [4.45423973e-01, 5.54576027e-01],
       [9.54576947e-01, 4.54230528e-02],
       [9.98800099e-01, 1.19990120e-03],
       [9.81270905e-01, 1.87290950e-02],
       [9.99599353e-01, 4.00646765e-04],
       [9.75231892e-01, 2.47681076e-02],
       [9.99721670e-01, 2.78330408e-04],
       [9.99985702e-01, 1.42984438e-05],
       [9.99783568e-01, 2.16432388e-04],
       [9.99918644e-01, 8.13560068e-05],
       [9.99145594e-01, 8.54406062e-04],
       [9.99999717e-01, 2.83405026e-07],
       [9.99999388e-01, 6.11971516e-07],
       [9.96257079e-01, 3.74292076e-03],
       [9.99951954e-01, 4.80455731e-05],
       [9.99935362e-01, 6.46377763e-05],
       [9.19148261e-01, 8.08517385e-02],
       [5.41069548e-01, 4.58930452e-01],
       [7.70095437e-01, 2.29904563e-01],
       [9.53824650e-01, 4.61753504e-02],
       [9.84177980e-01, 1.58220196e-02],
       [9.87144190e-01, 1.28558100e-02],
       [9.99826220e-01, 1.73780356e-04],
       [9.99997721e-01, 2.27860322e-06],
       [9.99960134e-01, 3.98661696e-05],
       [9.99989638e-01, 1.03623275e-05],
       [9.99460232e-01, 5.39767963e-04],
       [9.99969001e-01, 3.09986705e-05],
       [9.99918076e-01, 8.19244171e-05],
       [9.99928681e-01, 7.13185750e-05],
       [9.99999240e-01, 7.60217968e-07],
       [9.99998668e-01, 1.33170350e-06],
       [9.82520561e-01, 1.74794393e-02],
       [9.98850193e-01, 1.14980700e-03],
       [9.99992991e-01, 7.00869107e-06],
       [9.99990482e-01, 9.51824820e-06],
       [6.56066455e-01, 3.43933545e-01],
       [6.64327735e-01, 3.35672265e-01],
       [9.82533492e-01, 1.74665075e-02],
       [6.80824745e-01, 3.19175255e-01],
       [9.21651272e-01, 7.83487276e-02],
       [8.65458187e-01, 1.34541813e-01],
       [9.98777850e-01, 1.22215013e-03],
       [9.99256850e-01, 7.43150025e-04],
       [9.99896469e-01, 1.03531019e-04],
       [9.99950734e-01, 4.92660561e-05],
       [9.99841917e-01, 1.58083142e-04],
       [9.99995307e-01, 4.69280512e-06],
       [9.99198562e-01, 8.01438466e-04],
       [9.99991605e-01, 8.39542562e-06],
       [9.99997708e-01, 2.29194037e-06],
       [9.99999207e-01, 7.93317560e-07],
       [9.99998890e-01, 1.10992197e-06],
       [9.99999633e-01, 3.67386715e-07],
       [9.99995078e-01, 4.92245914e-06],
       [9.99852787e-01, 1.47213474e-04],
       [7.97698361e-01, 2.02301639e-01],
       [8.54648097e-01, 1.45351903e-01],
       [7.96662005e-01, 2.03337995e-01],
       [9.18624029e-01, 8.13759715e-02],
       [9.54791237e-01, 4.52087626e-02],
       [9.93858370e-01, 6.14163025e-03],
       [9.89287569e-01, 1.07124311e-02],
       [9.99233563e-01, 7.66436990e-04],
       [9.99919115e-01, 8.08848736e-05],
       [9.78655344e-01, 2.13446563e-02],
       [9.99996511e-01, 3.48946470e-06],
       [9.99982599e-01, 1.74007905e-05],
       [9.99986772e-01, 1.32283064e-05],
       [9.99995324e-01, 4.67620140e-06],
       [9.99994628e-01, 5.37165628e-06],
       [9.99973607e-01, 2.63926797e-05],
       [9.99998697e-01, 1.30250708e-06],
       [9.99991285e-01, 8.71547277e-06],
       [9.99999839e-01, 1.60784885e-07],
       [9.93756313e-01, 6.24368673e-03],
       [5.64753914e-01, 4.35246086e-01],
       [9.82254129e-01, 1.77458705e-02],
       [9.99985699e-01, 1.43005587e-05],
       [9.90591234e-01, 9.40876598e-03],
       [9.99147505e-01, 8.52494880e-04],
       [9.97857159e-01, 2.14284123e-03],
       [6.60707726e-01, 3.39292274e-01],
       [9.96251161e-01, 3.74883892e-03],
       [9.99862068e-01, 1.37931954e-04],
       [9.99927803e-01, 7.21966108e-05],
       [9.96537223e-01, 3.46277737e-03],
       [9.99972649e-01, 2.73506070e-05],
       [9.91555706e-01, 8.44429394e-03],
       [9.23128499e-01, 7.68715010e-02],
       [9.99424075e-01, 5.75925176e-04],
       [9.99999382e-01, 6.17878960e-07],
       [9.93605274e-01, 6.39472560e-03],
       [9.99994698e-01, 5.30173619e-06],
       [9.99999286e-01, 7.13704409e-07],
       [9.99332996e-01, 6.67003729e-04],
       [3.98493039e-01, 6.01506961e-01],
       [6.90791519e-01, 3.09208481e-01],
       [8.65536680e-01, 1.34463320e-01],
       [9.99991020e-01, 8.97993209e-06],
       [8.56575542e-01, 1.43424458e-01],
       [9.23329079e-01, 7.66709206e-02],
       [9.99899905e-01, 1.00094876e-04],
       [9.98412089e-01, 1.58791083e-03],
       [9.99982226e-01, 1.77740583e-05],
       [9.99543872e-01, 4.56128178e-04],
       [9.99093191e-01, 9.06809277e-04],
       [9.99756500e-01, 2.43499925e-04],
       [9.99996436e-01, 3.56431895e-06],
       [9.99988670e-01, 1.13301273e-05],
       [9.99994513e-01, 5.48688615e-06],
       [9.99995223e-01, 4.77651282e-06],
       [9.99998670e-01, 1.33044787e-06],
       [9.99941094e-01, 5.89055923e-05],
       [9.99999384e-01, 6.16132858e-07],
       [9.99989383e-01, 1.06168571e-05]])

In [36]:
pred_df=pd.DataFrame(predictions,columns=['p0','p1'])

In [37]:
test = pd.merge(df_test.reset_index().drop(columns=['index']),pred_df,left_index=True,right_index=True)
test = pd.merge(test,constructor_df,left_index=True,right_index=True)
test

,grid,positionOrder,year_x,circuitId,weather_warm,weather_cold,weather_dry,weather_wet,weather_cloudy,statusId_1,...,constructorId_208,constructorId_209,constructorId_210,constructorId_211,constructorId_213,constructorId_214,podium,p0,p1,constructorId
0,2,1,2019,1,0,0,0,0,0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1,0.871348,1.286516e-01,131
1,1,0,2019,1,0,0,0,0,0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2,0.403699,5.963005e-01,131
2,4,0,2019,1,0,0,0,0,0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3,0.870628,1.293719e-01,9
3,3,0,2019,1,0,0,0,0,0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0.780451,2.195494e-01,6
4,5,0,2019,1,0,0,0,0,0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0.950956,4.904353e-02,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
415,16,0,2019,24,1,0,0,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0.999995,4.776513e-06,51
416,18,0,2019,24,1,0,0,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0.999999,1.330448e-06,3
417,11,0,2019,24,1,0,0,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0.999941,5.890559e-05,5
418,19,0,2019,24,1,0,0,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0.999999,6.161329e-07,3
419,12,0,2019,24,1,0,0,0,0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0,0.999989,1.061686e-05,211

In [38]:
max_prob = test.groupby(['circuitId']).agg({'p1':'max'})
test = pd.merge(test, max_prob, how='left', on=['circuitId'])
test

,grid,positionOrder,year_x,circuitId,weather_warm,weather_cold,weather_dry,weather_wet,weather_cloudy,statusId_1,...,constructorId_209,constructorId_210,constructorId_211,constructorId_213,constructorId_214,podium,p0,p1_x,constructorId,p1_y
0,2,1,2019,1,0,0,0,0,0,1.0,...,0.0,0.0,0.0,0.0,0.0,1,0.871348,1.286516e-01,131,0.596301
1,1,0,2019,1,0,0,0,0,0,1.0,...,0.0,0.0,0.0,0.0,0.0,2,0.403699,5.963005e-01,131,0.596301
2,4,0,2019,1,0,0,0,0,0,1.0,...,0.0,0.0,0.0,0.0,0.0,3,0.870628,1.293719e-01,9,0.596301
3,3,0,2019,1,0,0,0,0,0,1.0,...,0.0,0.0,0.0,0.0,0.0,0,0.780451,2.195494e-01,6,0.596301
4,5,0,2019,1,0,0,0,0,0,1.0,...,0.0,0.0,0.0,0.0,0.0,0,0.950956,4.904353e-02,6,0.596301
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
415,16,0,2019,24,1,0,0,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0.999995,4.776513e-06,51,0.601507
416,18,0,2019,24,1,0,0,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0.999999,1.330448e-06,3,0.601507
417,11,0,2019,24,1,0,0,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0.999941,5.890559e-05,5,0.601507
418,19,0,2019,24,1,0,0,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0.999999,6.161329e-07,3,0.601507
419,12,0,2019,24,1,0,0,0,0,0.0,...,0.0,0.0,1.0,0.0,0.0,0,0.999989,1.061686e-05,211,0.601507

In [39]:
test.to_csv("testest.csv")

In [40]:
flag = []
for index, row in test.iterrows():
    if row['p1_x'] == row['p1_y']:
        if row['positionOrder']==1:
            flag.append(1)
        else:
            flag.append(0)
    else:
        flag.append(0)
        
test['flag'] = flag
test['flag'].sum()

10

In [41]:
flag = []
for index, row in test.iterrows():
    if row['p1_x'] == row['p1_y']:
        if row['podium'] in [1,2,3]:
            flag.append(1)
        else:
            flag.append(0)
    else:
        flag.append(0)
        
test['flag'] = flag
test['flag'].sum()

18

In [42]:
races = test.groupby(['year_x','circuitId']).agg('count')
races

                  grid  positionOrder  weather_warm  weather_cold  \
year_x circuitId
2019   1            20             20            20            20
       3            20             20            20            20
       4            20             20            20            20
       6            20             20            20            20
       7            20             20            20            20
       9            20             20            20            20
       10           20             20            20            20
       11           20             20            20            20
       13           20             20            20            20
       14           20             20            20            20
       15           20             20            20            20
       17           20             20            20            20
       18           20             20            20            20
       22           20             20            20            20
       24           20             20            20            20
       32           20             20            20            20
       34           20             20            20            20
       69           20             20            20            20
       70           20             20            20            20
       71           20             20            20            20
       73           20             20            20            20

                  weather_dry  weather_wet  weather_cloudy  statusId_1  \
year_x circuitId
2019   1                   20           20              20          20
       3                   20           20              20          20
       4                   20           20              20          20
       6                   20           20              20          20
       7                   20           20              20          20
       9                   20           20              20          20
       10                  20           20              20          20
       11                  20           20              20          20
       13                  20           20              20          20
       14                  20           20              20          20
       15                  20           20              20          20
       17                  20           20              20          20
       18                  20           20              20          20
       22                  20           20              20          20
       24                  20           20              20          20
       32                  20           20              20          20
       34                  20           20              20          20
       69                  20           20              20          20
       70                  20           20              20          20
       71                  20           20              20          20
       73                  20           20              20          20

                  statusId_2  statusId_3  ...  constructorId_210  \
year_x circuitId                          ...
2019   1                  20          20  ...                 20
       3                  20          20  ...                 20
       4                  20          20  ...                 20
       6                  20          20  ...                 20
       7                  20          20  ...                 20
       9                  20          20  ...                 20
       10                 20          20  ...                 20
       11                 20          20  ...                 20
       13                 20          20  ...                 20
       14                 20          20  ...                 20
       15                 20          20  ...                 20
       17                 20          20  ...                 20
       18                 20          20  ...                 20
       22                 20          20  ...                 20
       24                 20          20  ...                 20
       32                 20          20  ...                 20
       34                 20          20  ...                 20
       69                 20          20  ...                 20
       70                 20          20  ...                 20
       71                 20          20  ...                 20
       73                 20          20  ...                 20

                  constructorId_211  constructorId_213  constructorId_214  \
year_x circuitId
2019   1                         20                 20                 20
       3                         20                 20                 20
       4                         20                 20                 20
       6                         20                 20                 20
       7                         20                 20                 20
       9                         20                 20                 20
       10                        20                 20                 20
       11                        20                 20                 20
       13                        20                 20                 20
       14                        20                 20                 20
       15                        20                 20                 20
       17                        20                 20                 20
       18                        20                 20                 20
       22                        20                 20                 20
       24                        20                 20                 20
       32                        20                 20                 20
       34                        20                 20                 20
       69                        20                 20                 20
       70                        20                 20                 20
       71                        20                 20                 20
       73                        20                 20                 20

                  podium  p0  p1_x  constructorId  p1_y  flag
year_x circuitId
2019   1              20  20    20             20    20    20
       3              20  20    20             20    20    20
       4              20  20    20             20    20    20
       6              20  20    20             20    20    20
       7              20  20    20             20    20    20
       9              20  20    20             20    20    20
       10             20  20    20             20    20    20
       11             20  20    20             20    20    20
       13             20  20    20             20    20    20
       14             20  20    20             20    20    20
       15             20  20    20             20    20    20
       17             20  20    20             20    20    20
       18             20  20    20             20    20    20
       22             20  20    20             20    20    20
       24             20  20    20             20    20    20
       32             20  20    20             20    20    20
       34             20  20    20             20    20    20
       69             20  20    20             20    20    20
       70             20  20    20             20    20    20
       71             20  20    20             20    20    20
       73             20  20    20             20    20    20

[21 rows x 1079 columns]